# -*- coding: utf-8 -*-
"""Liner Regression with R.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OnXYTXZC2ESUHLsActU8YTZsBfD3huJo

# DATASET: Salarios Ciberseguridad



- Una colección de la escala salarial para las personas que trabajan en el area de la seguridad cibernética.
"""

install.packages('VIM')

install.packages('corrplot')

library(corrplot)

"""# CARGAMOS LIBRERIAS NECESARIAS"""

library(tidyverse)
library(VIM)

"""# CARGAMOS LOS DATOS"""

datos<- read.csv("salaries_cyber.csv", sep = ',')

"""# ANÁLISIS EXPLORATÓRIO DEL DATA-SET

**Vista general del dataset**
"""

head(datos)

"""**Para ver el nombre de las columnas**"""

names(datos)

"""**Muestra la estructura del Objeto 'datos'**"""

str(datos)

"""# **Convertimos todas las variables tipo 'chr' a una variable de tipo 'Factor'**"""

df <- datos%>%mutate_if(is.character, as.factor)
str(df)

df <- datos%>%mutate_if(is.factor, as.numeric)
str(df)

x <- as.numeric(df$job_title)
y <- df$salsalary_in_usdary

"""# **Buscamos y visualizamos los Valores Nulos**"""

aggr(df, plot = F, numbers = T, prop = T)

aggr(df, plot = T, numbers = T, prop = T, combined= F, sortVars = T, cex.axis=.7, gap=3)

"""# **Miramos la Matriz de Correlacion**"""

head(df)



plot(x=x,y=y)