---
title: "MNIST"
author: "willandru"
date: "21/11/2022"
output: html_document
---


# MNIST: Imagenes de números escritos a mano.


```{r}
N=4000

read.training = file("train-images.idx3-ubyte", "rb")
readBin(read.training,'integer',n=1,size=4,endian='big')
nrow = readBin(read.training,'integer',n=1,size=4,endian='big')
ncol = readBin(read.training,'integer',n=1,size=4,endian='big')
x = data.frame()
for(i in 1:N){m = readBin(read.training,'integer',n=28*28,size=1,signed=F);
    x <- rbind(x, m)}
     close(read.training)
     
     
read.labels = file("train-labels.idx1-ubyte", "rb")
readBin(read.labels,'integer',n=1,size=4,endian='big')
n = readBin(read.labels,'integer',n=1,size=4,endian='big')
y = readBin(read.labels,'integer',n=n,size=1,signed=F)
close(read.labels)
y=data.frame(sapply(as.numeric(y[1:N]), c))

df =x
df['Y'] <- y

```

```{r}
head(df)
```

```{r}
DF=df[(df$Y==0) | (df$Y==1),]

```

```{r}
set.seed(111)
split <- sort(sample(nrow(DF), nrow(DF)*0.7))
training <- DF[split,]
testing <- DF[-split,]
```

```{r}
log_model <- glm(as.factor(Y) ~ .-Y,
                 family = binomial,
                 data = training)
summary(log_model)
```

```{r}
probabilities <- predict(log_model, 
                       newdata = testing,
                       type = "response")
predictions <- ifelse(probabilities > 0.5, "1", "0")
trn_tab <- table(predictions, testing$Y)
```

```{r }

library("caret")
confusionMatrix(trn_tab, positive = "1")
```
























```{r}

```
























```{r}

```
```{r}

```
```{r}

```